name: 'Setup Stackgen'
description: 'Sets up Stackgen CLI and configures it'

inputs:
  stackgen-token:
    description: 'Stackgen API Token'
    required: true
  stackgen-url:
    description: 'Stackgen API URL'
    default: 'https://cloud.stackgen.com/'
    required: false
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Brew install stackgen
      shell: bash
      run: brew install appcd-dev/stackgen/stackgen

    - name: Run Stackgen version
      shell: bash
      run: stackgen version

    - name: Stackgen Configure
      shell: bash
      env:
        STACKGEN_TOKEN: ${{ inputs.stackgen-token }}
        STACKGEN_URL: ${{ inputs.stackgen-url }}
      run: stackgen configure
